### ISSUE TITLE
Auto define doesn't work

### ISSUE THREAD

**Issue by EmrecanD** [z1lc/AutoDefine#9] opened 2016-02-10 18:31 UTC
After properly getting the API key and setting up the add on, trying to use the feature with Ctrl + E or AD button gives out this error all the time:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
File "C:\Users\Morteza\Documents\Anki\addons\AutoDefineAddon\core.py", line 175, in <lambda>
editor._addButton("AutoDefine", lambda ed=editor: get_definition(ed),
File "C:\Users\Morteza\Documents\Anki\addons\AutoDefineAddon\core.py", line 57, in get_definition
etree = ET.parse(urllib.urlopen(url))
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/xml.etree.ElementTree", line 1183, in parse
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/xml.etree.ElementTree", line 656, in parse
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/xml.etree.ElementTree", line 1643, in feed
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/xml.etree.ElementTree", line 1507, in _raiseerror
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by z1lc** [comment] 2018-06-27 02:17
Duplicate of #6

**Closed by z1lc** 2018-06-27 02:17 UTC
